security:
  password_hashers:
    App\Entity\User\User: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User\User
        property: email
  firewalls:
    login:
      pattern: ^/api/auth
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: auth_login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    api:
      pattern: ^/api/
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/api/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto
      cost: 4 # Lowest possible value for bcrypt
      time_cost: 3 # Lowest possible value for argon
      memory_cost: 10 # Lowest possible value for argon
